### ISSUE TITLE
Content Updates

### ISSUE THREAD

**Issue by Maker-Mark** [CodeletApp/codelet-site#10]
## Tasks

- [ ] Reword Demo->Learn More
- [ ] New images per step! 
- [ ] Replaced React title logo for our own logo
